model_list:
  - model_name: qwen_asr
    litellm_params:
      model: hosted_vllm/Qwen/Qwen3-ASR-1.7B
      api_base: http://qwen_asr-srv:7088/v1
      api_key: "sk-1234"
  - model_name: gemini-flash-transcribe
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: os.environ/GEMINI_API_KEY

general_settings:
  disable_auth: true
  disable_database: true
