version: "3.8"

services:
  litellm:
    image: litellm/litellm:latest
    container_name: litellm-gateway
    platform: linux/amd64
    entrypoint: ["litellm"]
    command: ["--config", "/app/config.yaml", "--port", "4000"]
    environment:
      - LITELLM_DISABLE_DATABASE=true
      - LITELLM_DISABLE_AUTH=true
      - LITELLM_MASTER_KEY=sk-1234
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    ports:
      - "4000:4000"
    networks:
      - asr-net
    depends_on:
      - whisper_ms_precise-srv
      - whisperx-srv
      - qwen_asr-srv
  whisper_ms_precise-srv:
    build:
      context: vllm_inference_models/whisper
    container_name: whisper_ms_precise-srv
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["1"]
              capabilities: [gpu]
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "7086:7086"
    command: python -m app.main --host 0.0.0.0 --port 7086 --model mesolitica/Malaysian-whisper-large-v3-turbo-v3 --dtype bfloat16 --gpu-memory-utilization 0.3
    networks:
      - asr-net
  whisperx-srv:
    image: whisperx-api-server-cuda
    build:
      context: vllm_inference_models/whisperx
      dockerfile: Dockerfile.cuda
    container_name: whisperx-srv
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:7090/healthcheck || exit 1"]
    command: uvicorn --factory whisperx_api_server.main:create_app --host 0.0.0.0 --port 7090
    ports:
      - "7090:7090"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=7090
      - WHISPER__MODEL=large-v3
      - WHISPER__INFERENCE_DEVICE=cuda
      - WHISPER__DEVICE_INDEX=0
      - WHISPER__PRELOAD_MODEL=true
      - CUDA_VISIBLE_DEVICES=3
    volumes:
      - hugging_face_cache:/home/ubuntu/.cache/huggingface
      - torch_cache:/home/ubuntu/.cache/torch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["3"]
              capabilities: [gpu]
    networks:
      - asr-net
  qwen_asr-srv:
    build:
      context: vllm_inference_models/qwen_asr
    container_name: qwen_asr-srv
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["2"]
              capabilities: [gpu]
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    ports:
      - "7087:7087"
    command: vllm serve Qwen/Qwen3-ASR-1.7B --host 0.0.0.0 --port 7087
    networks:
      - asr-net

volumes:
  hugging_face_cache:
  torch_cache:

networks:
  asr-net:
    external: true
